const path = [
    {
        index:"1",
        name:'用户管理',
        icon:'el-icon-user-solid',
        children:[
            {
                name:'冻结用户',
                path:'/admin/user'
            },
            {
                name:'删除用户',
                path:'/admin/delete'
            },
        ]
    },
    {
        index:"2",
        name:'文章管理',
        icon:'el-icon-folder-opened',
        children:[
            {
                name:'置顶文章',
                path:'/admin/istop'
            },
            {
                name:'删除文章',
                path:'/admin/delnews'
            },
        ]
    },
    {
        index:"3",
        name:'请求处理',
        icon:'el-icon-message-solid',
        children:[
            {
                name:'举报处理',
                path:'/admin/report'
            },
        ]
    },
    {
        index:"4",
        name:'添加管理',
        icon:'el-icon-folder-add',
        children:[
            {
                name:'添加管理员',
                path:'/admin/addadmin'
            },
            {
                name:'删除用户',
                path:'/admin/deladmin'
            },
        ]
    },
    {
        index:"5",
        name:'权限管理',
        icon:'el-icon-s-operation',
        children:[
            {
                name:'权限列表',
                path:'/admin/rolelist'
            },
            {
                name:'权限分配',
                path:'/admin/rolepost'
            },
        ]
    },
]
export default  path
